### ISSUE TITLE
Reported wind directions are sometimes incorrect

### ISSUE THREAD

**Issue by BenjaminPelletier** [crestlinesoaring/ArduinoWeatherStation#1]
From Jimmy's email:

> we're experiencing some off directions on MArshall, don't know yet what it could be. Lance checked the raw data from the past week and noticed some incorrect alignments, and will look into that next week.

**Comment by lrocker** [comment]
Resolved by Jimmy finding the cabling had been inadvertently shorted in the tubing on the way to the windvane. Replaced cabling, ADC values are very solid and repeatable now.
